#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 18 16:23:38 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 2e61e368fc414cdf865d2ff4aed0b680 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TB_n_bit_register2_behav xil_defaultlib.TB_n_bit_register2 xil_defaultlib.glbl -log elaborate.log"
xelab -wto 2e61e368fc414cdf865d2ff4aed0b680 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TB_n_bit_register2_behav xil_defaultlib.TB_n_bit_register2 xil_defaultlib.glbl -log elaborate.log

